version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "while ! nc -z postgres 5432; do
        echo 'Waiting for postgres to be ready...'
        sleep 2
      done &&
      while ! nc -z mysql 3306; do
        echo 'Waiting for mysql to be ready...'
        sleep 2
      done &&
      python manage.py makemigrations auth_service &&
      python manage.py makemigrations system_a &&
      python manage.py makemigrations system_b &&
      python manage.py migrate auth_service --database=default &&
      python manage.py migrate system_a --database=system_a &&
      python manage.py migrate system_b --database=system_b &&
      python manage.py collectstatic --noinput &&
      gunicorn sso_project.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_started
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=sso_project.settings
      - POSTGRES_HOST=postgres
      - MYSQL_HOST=mysql
      - MONGODB_HOST=mongodb
      - REDIS_HOST=redis

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sso_auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  postgres_replica:
    image: postgres:14
    restart: always
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sso_auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    depends_on:
      - postgres

  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=system_a_db
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  postgres_replica_data:
  mysql_data:
  mongodb_data:
